services:

  incidencies-app:

    build: .

    container_name: incidencies-project-1DAM

    env_file:

      - .env

    volumes:

      - .:/app

    ports:

      - "3000:3000"

    depends_on:

      - db



  db:

    image: mysql:5.7

    container_name: incidencies-db-container

    env_file:

      - .env

    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    ports:

      - "3306:3306"



  adminer:

    image: adminer

    container_name: incidencies-adminer

    depends_on:

    - db

    ports:

    - "8080:8080"